apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p8pod
  name: p8pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p8pod
    spec:
      containers:
      - image: kamekamepon2/piper8container:latest
        imagePullPolicy: IfNotPresent
        name: piper8container
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: APP
          value: "app.py"
        - name: RABBITMQ_IP
          value: "rabbitmq"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD 
          value: "guest"
        - name: MSTEAMS_URL 
          value: "https://dell.webhook.office.com/webhookb2/e0a540f3-e6bb-4273-83f9-e82877290ce8@945c199a-83a2-4e80-9f8c-5a91be5752dd/IncomingWebhook/8ab059ee2edd43a49cf1a684e145e888/767f097b-3df4-4cce-8ff8-b94533a5e92b"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
