apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: amqp
    nodePort: 5672
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: gui
    nodePort: 15672
    protocol: TCP
    port: 15672
    targetPort: 15672
